---
# argument spec file for nerdynik.workstation.sublime-text

argument_specs:
  main:
    short_description: Role description.
    options:
      sublime-text_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
