---
argument_specs:
  main:
    short_description: Role to install Sublime Text
    description: >
      Role to install Sublime Text. 
      Taking into account OS weather to install Cask (MacOS) or Key, Repo, & Package (Linux - Debian/Redhat)
