---
galaxy_info:
  author: NerdyNik
  description: Install Sublime Text
  company: NerdyNik
  issue_tracker_url: https://github.com/nerdynick/ansible-galaxy/issues
  license: BSD-3-Clause
  min_ansible_version: "2.14"
  galaxy_tags: []
