namespace: nerdynik
name: k8s
version: 0.0.1
readme: README.md
authors:
  - NerdyNik
description: >
  A collection of roles to help deploying various applications
  into K8s based homelabs.
license:
  - BSD-3-Clause
tags:
  - homelab
repository: https://github.com/nerdynick/ansible-galaxy.git
homepage: https://github.com/nerdynick/ansible-galaxy
issues: https://github.com/nerdynick/ansible-galaxy/issues