---
- name: Restart Plex
  ansible.builtin.service:
    name: plexmediaserver
    state: restarted
- name: Reload Plex
  ansible.builtin.service:
    name: plexmediaserver
    state: reloaded
  notify:
    - Restart Plex
