---
- name: Installing Sublime Text
  ansible.builtin.include_role:
    name: nerdynik.general.multiplatform_installer
  vars:
    multiplatform_installer_package: sublime-text
    multiplatform_installer_apt_repo:
      name: sublime-text
      url: https://download.sublimetext.com/
      dist: apt/stable/
      key_name: sublimehq-pub
      key_url: https://download.sublimetext.com/sublimehq-pub.gpg
    multiplatform_installer_yum_repo:
      name: sublime-text
      url: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
      key_url: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
