---
# argument spec file for nerdynik.workstation.multiplatform_installer

argument_specs:
  main:
    short_description: Role description.
    options:
      multiplatform_installer_my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
