---
argument_specs:
  main:
    short_description:  A role to help install a given package/application across multiple different platforms.
    version_added: 0.0.1
    author: 
      - NerdyNik
    options:
      multiplatform_installer_package:
        type: str
        description: Optional Default package name to use if all/most installation methods share the same name
        default: None
      multiplatform_installer_deb_url:
        type: str
        description: Optional URL to download a `.deb` file from and install it
        default: None
      multiplatform_installer_apt_package:
        default: "{{ multiplatform_installer_package }}"
      multiplatform_installer_apt_repo:
        type: dict
        description: ""
        default:
          dist: stable
        options:
          key_name:
            type: str
            description: >
              The name to give the key. This is effectively the name of the key file store on the filesystem.
              Of note the extension `.asc` will automatically be added to the saved file into the apt keyring.
          key_url:
            type: str
            description: URL to fetch the signing key from
          url:
            type: str
            description: URL of the Repo
          dist:
            type: str
            description: Distribution name, or in some case the path from root on the repo, this can also sometimes be the codename for the release.
          name:
            type: str
            description: The name to give when creating and local source/repo files to define out the repo
      multiplatform_installer_yum_package:
        default: "{{ multiplatform_installer_package }}"
      multiplatform_installer_yum_repo:
        type: dict
        description: ""
        default:
          dist: stable
        options:
          key_name:
            type: str
            description: >
              The name to give the key. This is effectively the name of the key file store on the filesystem.
          key_url:
            type: str
            description: URL to fetch the signing key from
          url:
            type: str
            description: URL of the Repo
          dist:
            type: str
            description: Distribution name, or in some case the path from root on the repo, this can also sometimes be the codename for the release.
          name:
            type: str
            description: The name to give when creating and local source/repo files to define out the repo
      multiplatform_installer_brew_package:
        type: str
        description: Package or Cask name to install
        default: "{{ multiplatform_installer_package }}"
      multiplatform_installer_brew_is_cask:
        type: bool
        description: Weather the package to install should be installed via a Cask or just from the tap.
        default: false