---
galaxy_info:
  author: NerdyNik
  description: >
    A role to help install a given package/application across multiple different platforms.
    Right now it supports MacOS vis Brew, Debian like via Apt, and Redhat like via Yum.
    For MacOS, this supports installing standard Homebrew packages or casks.
    For Deb, this supports apt install, adding Apt repos and installing, and URL fetching `.deb` files and installing
    For Yum, this supports TBD
  company: NerdyNik
  license: BSD-3-Clause
  min_ansible_version: "2.14"
  galaxy_tags: []
dependencies: []
