---
# defaults file for nerdynik.workstation.multiplatform_installer

# Repo Structure:
#   url - Url to the repo
#   name - Name to give to the sources file
#   dist - Distribution or path from repo root. Will assume `stable` if undefined.
# Key Structure:
#   url - Url to fetch the GPG Key from
#   name - Name to give to the GPG key. `.asc` will auto be appended for DEB/Apt based installs

# Global Settings
multiplatform_installer_package: ""

# Redhat like Linux Settings
multiplatform_installer_rpm_url: ""
multiplatform_installer_yum_package: "{{ multiplatform_installer_package }}"
multiplatform_installer_yum_repo: {}
#   url:
#   name:
#   dist:
#   key_url:
#   key_name:

# Debian like Linux Settings
multiplatform_installer_deb_url: ""
multiplatform_installer_apt_package: "{{ multiplatform_installer_package }}"
multiplatform_installer_apt_repo: {}
#   url:
#   name:
#   dist:
#   key_url:
#   key_name:

# MacOS Settings
multiplatform_installer_brew_package: "{{ multiplatform_installer_package }}"
multiplatform_installer_brew_is_cask: false
